// <auto-generated />
using Demo.RazorYEF.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.RazorYEF.Data.Migrations
{
    [DbContext(typeof(RazorDbContext))]
    partial class RazorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Demo.RazorYEF.Entidades.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Frescos"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Despensa"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Congelados"
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Bebidas"
                        });
                });

            modelBuilder.Entity("Demo.RazorYEF.Entidades.Producto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("UrlImagen")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Calibre: 3 PIEZAS",
                            Nombre = "Maíz dulce cocido al vacío 400 gr",
                            UrlImagen = "/images/10477990608926.jpg"
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Malla 2 Kg",
                            Nombre = "Cebolla malla 2 Kg",
                            UrlImagen = "/images/8847033073694.png"
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 1,
                            Descripcion = "Salchichas con queso",
                            Nombre = "OSCAR MAYER salchichas con queso envase 200 gr",
                            UrlImagen = "/images/10971771764766.jpg"
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 1,
                            Descripcion = "Naranja 2Kg",
                            Nombre = "Naranja premium bolsa 2 Kg",
                            UrlImagen = "/images/11272783953950.jpg"
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 1,
                            Descripcion = "Tomate rosa",
                            Nombre = "Tomate rosa de la reina unidad (peso aprox. 900 gr)",
                            UrlImagen = "/images/10937809993758.jpg"
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 1,
                            Descripcion = "Melón",
                            Nombre = "Melón selección unidad (3.5 Kg aprox.)",
                            UrlImagen = "/images/producto17p.jpg"
                        },
                        new
                        {
                            Id = 7,
                            CategoriaId = 2,
                            Descripcion = "Aceite girasol",
                            Nombre = "KOIPE Sol aceite girasol botella 1 lt",
                            UrlImagen = "/images/11160116756510.jpg"
                        },
                        new
                        {
                            Id = 8,
                            CategoriaId = 2,
                            Descripcion = "Leche desnatada",
                            Nombre = "LAUKI leche desnatada envase 1 lt",
                            UrlImagen = "/images/11238530220062.jpg"
                        },
                        new
                        {
                            Id = 9,
                            CategoriaId = 2,
                            Descripcion = "Cereales",
                            Nombre = "KELLOGGS cereales corn flakes caja 500 gr",
                            UrlImagen = "/images/11265824653342.jpg"
                        },
                        new
                        {
                            Id = 10,
                            CategoriaId = 2,
                            Descripcion = "FINI golosinas",
                            Nombre = "FINI golosinas jelly cola bolsa 100 gr",
                            UrlImagen = "/images/10905632178206.jpg"
                        },
                        new
                        {
                            Id = 11,
                            CategoriaId = 3,
                            Descripcion = "Trenza",
                            Nombre = "RAPUN trenza de Huesca caja 450 gr",
                            UrlImagen = "/images/10465404551198.jpg"
                        },
                        new
                        {
                            Id = 110,
                            CategoriaId = 3,
                            Descripcion = "Pizza",
                            Nombre = "DR OETKER ristorante pizza spinaci caja 390 gr",
                            UrlImagen = "/images/11106487664670.jpg"
                        },
                        new
                        {
                            Id = 12,
                            CategoriaId = 4,
                            Nombre = "Agua 50cl",
                            UrlImagen = "/images/producto1p.jpg"
                        },
                        new
                        {
                            Id = 13,
                            CategoriaId = 4,
                            Nombre = "Kas Naranja",
                            UrlImagen = "/images/producto2p.jpg"
                        },
                        new
                        {
                            Id = 14,
                            CategoriaId = 4,
                            Nombre = "Kas Limón",
                            UrlImagen = "/images/producto3p.jpg"
                        },
                        new
                        {
                            Id = 15,
                            CategoriaId = 4,
                            Nombre = "Pepsi",
                            UrlImagen = "/images/producto4p.jpg"
                        },
                        new
                        {
                            Id = 16,
                            CategoriaId = 4,
                            Nombre = "Pepsi Light",
                            UrlImagen = "/images/producto5p.jpg"
                        },
                        new
                        {
                            Id = 17,
                            CategoriaId = 4,
                            Nombre = "Pepsi Max",
                            UrlImagen = "/images/producto6p.jpg"
                        },
                        new
                        {
                            Id = 18,
                            CategoriaId = 4,
                            Nombre = "Seven Up",
                            UrlImagen = "/images/producto9p.jpg"
                        });
                });

            modelBuilder.Entity("Demo.RazorYEF.Entidades.Producto", b =>
                {
                    b.HasOne("Demo.RazorYEF.Entidades.Categoria", "Categoria")
                        .WithMany("Productos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Demo.RazorYEF.Entidades.Categoria", b =>
                {
                    b.Navigation("Productos");
                });
#pragma warning restore 612, 618
        }
    }
}
